#!/usr/bin/env python

import os, sys

argv=sys.argv
str = []
shb= ""
fname= ""

for i in range(len(argv)):
    str = []
    if not ( i == 0):
      for x in argv[i]:
        str=str+[x]
    try:
      if (str[0] == "-"):
        if argv[i].count( "s"):
          #print("flg")
          shb=argv[i+1]
        if argv[i].count("f"):
          fname=argv[i+1]
    except:
      pass
#print(str)
import subprocess
shb=subprocess.check_output(["which",shb])
shb=shb.decode('utf-8')
shb=shb.replace("\n","")
#print(shb)
##fname=fname.decode('utf-8')
#print(fname)
def ifarg():
  f=open(fname,'r')
  str2=[]
  for x in f:
    str2=str2+[x]
  print("old str2: {}".format(str2))
  if str2[0].count("#!"):
    del(str2[0])
  #str2="#!{0}\n{1}".format(shb,str2)
  str2.insert(0,"#!{0}\n".format(shb))
  print("new str2: {}".format(str2))
  f.close()
  f=open(fname,"w")
  for x in str2:
    f.write(x)
  f.close()
ifarg()
